exclude_paths:
  - tmp
  - vendor

detectors:
  DuplicateMethodCall:
    exclude:
      - RFC::Web::Link::Parsers::Line#process
  FeatureEnvy:
    exclude:
      - RFC::Web::Link::Parsers::Line#process
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - RFC::Web::Link::Parsers::Pair#call
