exclude_paths:
  - tmp
  - vendor

detectors:
  ControlParameter:
    exclude:
      - RFC::Web::Link::Parsers::Header#call
  DuplicateMethodCall:
    exclude:
      - RFC::Web::Link::Parsers::Line#process
  FeatureEnvy:
    exclude:
      - RFC::Web::Link::Parsers::Line#process
  LongParameterList:
    enabled: false
  NestedIterators:
    exclude:
      - RFC::Web::Link::Models::Link#find_pair
      - RFC::Web::Link::Models::Link#pair?
  TooManyInstanceVariables:
    exclude:
      - RFC::Web::Link::Parsers::List
  TooManyStatements:
    exclude:
      - RFC::Web::Link::Parsers::List#initialize
      - RFC::Web::Link::Parsers::Pair#call
